sonar.projectKey=harness-ci-demo
sonar.projectName=Harness CI/CD Demo
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
