apiVersion: v1
kind: Secret
metadata:
  name: nexus-aws-docker-pull-secret
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: demo-java-maven
    app.kubernetes.io/component: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{.Values.nexus.registry}}": {
          "username": "{{.Values.nexus.username}}",
          "password": "{{.Values.nexus.password}}"
        }
      }
    }
