{{- if .Values.imagePullSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-aws-docker-pull-secret
  namespace: {{.Values.namespace}}
  annotations:
    harness.io/skip-versioning: "true"
  labels:
    app.kubernetes.io/name: demo-java-maven
    app.kubernetes.io/component: registry-credentials
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{.Values.imagePullSecret}}
{{- end}}
